development:
  adapter: postgresql
  encoding: unicode
  database: aaaamilne_development
  host: localhost
  pool: 16
  username: aaaamilne
  password: 

test: &test
  adapter: postgresql
  encoding: unicode
  database: aaaamilne_test
  host: localhost
  pool: 5
  username: aaaamilne
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: aaaamilne_production
  host: localhost
  pool: 5
  username: aaaamilne
  password: 

cucumber:
  <<: *test