development:
  adapter: postgresql
  encoding: unicode
  database: epldb_dev
  host: localhost
  pool: 16
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: aaaamilne_test
  host: localhost
  pool: 5
  username: aaaamilne
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: epldb_dev
  host: localhost
  pool: 16
  username: postgres
  password:
